In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import pandas as pd

In [6]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Classical Functions (Dimesion = 100) [F1 - F13]

In [7]:
classical_df = pd.read_csv(r'D:\ProfAjaz\Experiment#1\archived_result\new_result\results_f1_f13\benchmark_summary.csv')

In [8]:
classical_df.columns.to_list()

['Function',
 'Optimizer',
 'Mean_Fitness',
 'Std_Fitness',
 'Mean_Expl',
 'Mean_Exploit',
 'AUC_Expl',
 'AUC_Exploit',
 'Mean_Expl_Hussain',
 'Mean_Exploit_Hussain',
 'AUC_Expl_Hussain',
 'AUC_Exploit_Hussain',
 'Avg_Conv_Iter',
 'Avg_Xover_Point',
 'Avg_Xover_Hussain']

In [9]:
fitness_cols = ['Mean_Fitness', 'Std_Fitness']
percent_cols = ['Mean_Expl', 'Mean_Exploit', 'AUC_Expl', 'AUC_Exploit', 
                'Mean_Expl_Hussain', 'Mean_Exploit_Hussain', 'AUC_Expl_Hussain', 'AUC_Exploit_Hussain']
iter_cols = ['Avg_Conv_Iter', 'Avg_Xover_Point', 'Avg_Xover_Hussain']


for col in fitness_cols + percent_cols + iter_cols:
    classical_df[col] = pd.to_numeric(classical_df[col], errors='coerce')


summary_df = classical_df.groupby('Optimizer').agg({
    'Mean_Fitness': 'mean',
    'Std_Fitness': 'mean',
    'Mean_Expl': 'mean',
    'Mean_Exploit': 'mean',
    'AUC_Expl': 'mean',
    'AUC_Exploit': 'mean',
    'Mean_Expl_Hussain': 'mean',
    'Mean_Exploit_Hussain': 'mean',
    'Avg_Conv_Iter': 'mean',
    'Avg_Xover_Point': 'mean',
    'Avg_Xover_Hussain': 'mean'
}).reset_index()


display_df = summary_df.copy()

for col in fitness_cols:
    display_df[col] = display_df[col].apply(lambda x: f"{x:.2e}")


for col in percent_cols:
    if col in display_df.columns:
        display_df[col] = display_df[col].apply(lambda x: f"{x:.2f}")


for col in iter_cols:
    display_df[col] = display_df[col].round(0).astype(int)

print("--- SUMMARY AVERAGED (F1-F13 100D) ---")
print(display_df.to_string(index=False))

--- SUMMARY AVERAGED (F1-F13 100D) ---
Optimizer Mean_Fitness Std_Fitness Mean_Expl Mean_Exploit AUC_Expl AUC_Exploit Mean_Expl_Hussain Mean_Exploit_Hussain  Avg_Conv_Iter  Avg_Xover_Point  Avg_Xover_Hussain
     AGOA    -2.10e+03    1.90e+02     41.22        58.78    41.09       58.71             43.99                56.01            499              132                140
       DE     1.04e+06    9.25e+05     28.17        71.83    28.05       71.75             27.44                72.56            231              113                110
      EES    -1.59e+03    1.11e+02      3.62        96.38     3.54       96.26              4.46                95.54             46               11                 16
      GWO    -1.22e+03    1.62e+02      5.93        94.07     5.83       93.97              5.93                94.07             84               12                 12
      PSO     5.05e+07    7.53e+07      0.86        99.14     0.76       99.04              0.85                99.15              7                1                  1

In [10]:
pd.read_csv(r'D:\ProfAjaz\Experiment#1\archived_result\new_result\results_f1_f13\friedman_ranks.csv')

   Function Optimizer  Rank
0        F1       GWO     1
1        F1       EES     2
2        F1      AGOA     3
3        F1        DE     4
4        F1       PSO     5
5        F2       EES     1
6        F2       GWO     2
7        F2      AGOA     3
8        F2        DE     4
9        F2       PSO     5
10       F3       EES     1
11       F3       GWO     2
12       F3      AGOA     3
13       F3        DE     4
14       F3       PSO     5
15       F4       EES     1
16       F4       GWO     2
17       F4      AGOA     3
18       F4       PSO     4
19       F4        DE     5
20       F5       EES     1
21       F5       GWO     2
22       F5      AGOA     3
23       F5        DE     4
24       F5       PSO     5
25       F6       GWO     1
26       F6       EES     2
27       F6      AGOA     3
28       F6        DE     4
29       F6       PSO     5
30       F7       EES     1
31       F7       GWO     2
32       F7      AGOA     3
33       F7        DE     4
34       F7       PSO     5
35       F8      AGOA     1
36       F8       GWO     2
37       F8       EES     3
38       F8        DE     4
39       F8       PSO     5
40       F9       EES     1
41       F9       GWO     2
42       F9      AGOA     3
43       F9        DE     4
44       F9       PSO     5
45      F10       EES     1
46      F10       GWO     2
47      F10      AGOA     3
48      F10        DE     4
49      F10       PSO     5
50      F11       EES     1
51      F11       GWO     2
52      F11      AGOA     3
53      F11        DE     4
54      F11       PSO     5
55      F12      AGOA     1
56      F12       EES     2
57      F12       GWO     3
58      F12        DE     4
59      F12       PSO     5
60      F13      AGOA     1
61      F13       GWO     2
62      F13       EES     3
63      F13        DE     4
64      F13       PSO     5

In [11]:
classical_df[['Function', 'Optimizer', 'Mean_Expl', 'Mean_Exploit', 'AUC_Expl', 'AUC_Exploit', 'Mean_Expl_Hussain', 'Mean_Exploit_Hussain',
              'AUC_Expl_Hussain', 'AUC_Exploit_Hussain',	'Avg_Conv_Iter',	'Avg_Xover_Point',	'Avg_Xover_Hussain']]

,Function,Optimizer,Mean_Expl,Mean_Exploit,AUC_Expl,AUC_Exploit,Mean_Expl_Hussain,Mean_Exploit_Hussain,AUC_Expl_Hussain,AUC_Exploit_Hussain,Avg_Conv_Iter,Avg_Xover_Point,Avg_Xover_Hussain
0,F1,GWO,2.749853,9.725015e+01,2.649853,9.715015e+01,2.749853,97.250147,2.649853,97.150147,37.300000,6.033333,6.033333
1,F1,PSO,0.872935,9.912706e+01,0.772935,9.902706e+01,0.849530,99.150470,0.751056,99.048944,6.600000,1.333333,1.333333
2,F1,DE,9.750353,9.024965e+01,9.649806,9.015019e+01,9.822226,90.177774,9.720939,90.079061,96.700000,26.233333,26.433333
3,F1,AGOA,31.028814,6.897119e+01,30.911569,6.888843e+01,33.601158,66.398842,33.474181,66.325819,499.000000,44.833333,50.400000
4,F1,EES,1.239677,9.876032e+01,1.174988,9.862461e+01,2.004024,97.995976,1.903823,97.895776,17.100000,2.533333,7.833333
5,F2,GWO,2.749132,9.725087e+01,2.649132,9.715087e+01,2.749132,97.250868,2.649132,97.150868,35.933333,6.500000,6.500000
6,F2,PSO,0.935482,9.906452e+01,0.835473,9.896453e+01,0.923791,99.076209,0.824498,98.975502,6.733333,1.300000,1.300000
7,F2,DE,15.715220,8.428478e+01,15.614831,8.418517e+01,15.753242,84.246758,15.652601,84.147399,168.133333,56.833333,57.100000
8,F2,AGOA,31.105302,6.889470e+01,30.988082,6.881192e+01,33.629229,66.370771,33.502506,66.297494,499.000000,49.466667,55.166667
9,F2,EES,2.275035,9.772497e+01,2.179633,9.761997e+01,2.387488,97.612512,2.287292,97.512307,24.400000,8.366667,8.833333
10,F3,GWO,9.623268,9.037673e+01,9.523260,9.027674e+01,9.623268,90.376732,9.523260,90.276740,156.666667,8.433333,8.433333
11,F3,PSO,0.807736,9.919226e+01,0.707736,9.909226e+01,0.807736,99.192264,0.707736,99.092264,7.933333,1.433333,1.433333
12,F3,DE,45.881244,5.411876e+01,45.763715,5.403629e+01,43.777173,56.222827,43.664950,56.135050,494.300000,196.066667,180.833333
13,F3,AGOA,60.243874,3.975613e+01,60.107172,3.969283e+01,64.604034,35.395966,64.457458,35.342542,499.000000,374.533333,379.566667
14,F3,EES,4.436326,9.556367e+01,4.344892,9.545471e+01,4.851174,95.148826,4.750974,95.048625,54.133333,13.966667,16.533333
15,F4,GWO,13.516587,8.648341e+01,13.416586,8.638341e+01,13.516587,86.483413,13.416586,86.383414,138.700000,68.766667,68.766667
16,F4,PSO,0.990664,9.900934e+01,0.890664,9.890934e+01,0.951796,99.048204,0.854202,98.945798,8.033333,1.466667,1.466667
17,F4,DE,100.000000,2.453756e-10,99.800000,2.448848e-10,100.000000,0.000000,99.800000,0.000000,499.000000,500.000000,500.000000
18,F4,AGOA,65.901109,3.409889e+01,65.761789,3.403821e+01,70.780831,29.219169,70.631124,29.168876,499.000000,403.966667,436.966667
19,F4,EES,0.994941,9.900506e+01,0.934166,9.886543e+01,1.800678,98.199322,1.700477,98.099122,14.900000,1.000000,5.400000
20,F5,GWO,3.309979,9.669002e+01,3.209979,9.659002e+01,3.309979,96.690021,3.209979,96.590021,46.566667,6.433333,6.433333
21,F5,PSO,0.708272,9.929173e+01,0.608272,9.919173e+01,0.700332,99.299668,0.600983,99.199017,4.900000,1.466667,1.466667
22,F5,DE,12.288628,8.771137e+01,12.185613,8.761439e+01,12.311690,87.688310,12.208477,87.591523,108.900000,31.700000,31.766667
23,F5,AGOA,31.052526,6.894747e+01,30.936003,6.886400e+01,33.738491,66.261509,33.611814,66.188186,499.000000,44.600000,50.366667
24,F5,EES,1.387119,9.861288e+01,1.317869,9.848173e+01,2.053790,97.946210,1.953588,97.846011,18.900000,3.500000,7.833333
25,F6,GWO,2.843679,9.715632e+01,2.743678,9.705632e+01,2.843679,97.156321,2.743678,97.056322,36.833333,5.933333,5.933333
26,F6,PSO,0.937644,9.906236e+01,0.837638,9.896236e+01,0.888265,99.111735,0.791203,99.008797,6.633333,1.366667,1.366667
27,F6,DE,9.889771,9.011023e+01,9.789150,9.001085e+01,9.960625,90.039375,9.859273,89.940727,95.866667,26.100000,26.400000
28,F6,AGOA,30.672233,6.932777e+01,30.556084,6.924392e+01,33.832916,66.167084,33.704803,66.095197,499.000000,40.266667,46.666667
29,F6,EES,1.530104,9.846990e+01,1.460967,9.833863e+01,2.329857,97.670143,2.229424,97.570175,19.066667,2.933333,8.100000
30,F7,GWO,4.103022,9.589698e+01,4.003016,9.579698e+01,4.103022,95.896978,4.003016,95.796984,46.366667,6.200000,6.200000
31,F7,PSO,0.779627,9.922037e+01,0.679608,9.912039e+01,0.774580,99.225420,0.674985,99.125015,5.566667,1.333333,1.333333
32,F7,DE,12.881401,8.711860e+01,12.777305,8.702270e+01,12.917915,87.082085,12.813521,86.986479,113.600000,31.433333,31.500000
33,F7,AGOA,32.181326,6.781867e+01,32.060866,6.773913e+01,34.850807,65.149193,34.720374,65.079626,499.000000,37.900000,43.066667
34,F7,EES,1.875448,9.812455e+01,1.803451,9.799615e+01,2.680984,97.319016,2.580479,97.219120,20.066667,4.066667,8.533333
35,F8,GWO,19.038051,8.096195e+01,18.937927,8.086207e+01,19.038051,80.961949,18.937927,80.862073,337.100000,12.533333,12.533333
36,F8,PSO,1.038227,9.896177e+01,0.938227,9.886177e+01,1.038227,98.961773,0.938227,98.861773,8.100000,1.266667,1.266667
37,F8,DE,81.674111,1.832589e+01,81.519273,1.828073e+01,74.064098,25.935902,73.923589,25.876411,499.000000,435.733333,417.900000
38,F8,AGOA,95.477836,4.522164e+00,95.292459,4.507541e+00,93.485319,6.514681,93.303764,6.496236,499.000000,500.000000,500.000000
39,F8,EES,26.307143,7.369286e+01,26.227219,7.357238e+01,29.429743,70.570257,29.341354,70.458245,329.733333,87.766667,108.866667
40,F9,GWO,5.758206,9.424179e+01,5.658196,9.414180e+01,5.758206,94.241794,5.658196,94.141804,75.333333,6.833333,6.833333
41,F9,PSO,0.955096,9.904490e+01,0.855096,9.894490e+01,0.931351,99.068649,0.833087,98.966913,8.866667,1.266667,1.266667
42,F9,DE,29.188470,7.081153e+01,29.075732,7.072427e+01,29.343796,70.656204,29.230452,70.569548,477.200000,35.700000,36.766667
43,F9,AGOA,36.211483,6.378852e+01,36.091385,6.370861e+01,39.509530,60.490470,39.378476,60.421524,499.000000,65.866667,79.733333
44,F9,EES,1.310483,9.868952e+01,1.246387,9.855321e+01,2.247659,97.752341,2.147510,97.652089,20.066667,1.866667,7.733333
45,F10,GWO,2.800383,9.719962e+01,2.700383,9.709962e+01,2.800383,97.199617,2.700383,97.099617,38.033333,6.266667,6.266667
46,F10,PSO,0.888522,9.911148e+01,0.788522,9.901148e+01,0.888522,99.111478,0.788522,99.011478,5.900000,1.366667,1.366667
47,F10,DE,10.525007,8.947499e+01,10.422506,8.937749e+01,10.322707,89.677293,10.222126,89.577874,105.766667,26.766667,26.066667
48,F10,AGOA,30.129701,6.987030e+01,30.013496,6.978650e+01,32.724337,67.275663,32.598142,67.201858,499.000000,38.533333,43.733333
49,F10,EES,1.061091,9.893891e+01,0.997697,9.880190e+01,1.776595,98.223405,1.676413,98.123186,15.733333,1.300000,5.600000
50,F11,GWO,2.716215,9.728379e+01,2.616215,9.718379e+01,2.716215,97.283785,2.616215,97.183785,37.066667,5.866667,5.866667
51,F11,PSO,0.815044,9.918496e+01,0.715044,9.908496e+01,0.783545,99.216455,0.685631,99.114369,6.166667,1.300000,1.300000
52,F11,DE,9.711793,9.028821e+01,9.611341,9.018866e+01,9.793194,90.206806,9.691890,90.108110,98.866667,25.000000,25.300000
53,F11,AGOA,30.503921,6.949608e+01,30.387665,6.941234e+01,33.355244,66.644756,33.228147,66.571853,499.000000,40.966667,46.733333
54,F11,EES,1.430293,9.856971e+01,1.354820,9.844478e+01,2.053484,97.946516,1.953284,97.846315,20.166667,2.800000,6.966667
55,F12,GWO,4.107378,9.589262e+01,4.007374,9.579263e+01,4.107378,95.892622,4.007374,95.792626,55.433333,6.333333,6.333333
56,F12,PSO,0.738673,9.926133e+01,0.638673,9.916133e+01,0.738673,99.261327,0.638673,99.161327,6.166667,1.300000,1.300000
57,F12,DE,15.263366,8.473663e+01,15.158465,8.464154e+01,15.279781,84.720219,15.174766,84.625234,134.366667,40.366667,40.400000
58,F12,AGOA,30.338085,6.966191e+01,30.222643,6.957736e+01,33.530539,66.469461,33.402915,66.397085,499.000000,37.866667,43.766667
59,F12,EES,1.607346,9.839265e+01,1.531113,9.826849e+01,2.183898,97.816102,2.083671,97.715928,19.200000,4.033333,7.500000
60,F13,GWO,3.789391,9.621061e+01,3.689389,9.611061e+01,3.789391,96.210609,3.689389,96.110611,49.733333,6.433333,6.433333
61,F13,PSO,0.719265,9.928073e+01,0.619265,9.918073e+01,0.717247,99.282753,0.617438,99.182562,4.600000,1.200000,1.200000
62,F13,DE,13.414751,8.658525e+01,13.310941,8.648906e+01,13.437420,86.562580,13.333427,86.466573,114.666667,35.366667,35.366667
63,F13,AGOA,30.953253,6.904675e+01,30.837792,6.896221e+01,34.185089,65.814911,34.057594,65.742406,499.000000,41.733333,48.433333
64,F13,EES,1.565988,9.843401e+01,1.489888,9.830971e+01,2.117681,97.882319,2.017480,97.782119,21.300000,4.633333,7.100000

In [12]:
df_total = classical_df 


corr_val, p_val = stats.spearmanr(df_total['Mean_Expl'], df_total['Mean_Expl_Hussain'])

print(f"--- Spearman Correlation Results F1 - F13 (100D) ---")
print(f"Correlation Coefficient: {corr_val:.4f}")
print(f"P-value: {p_val:.4e}")

--- Spearman Correlation Results F1 - F13 (100D) ---
Correlation Coefficient: 0.9982
P-value: 1.9085e-78

# Classical F14-F23

In [13]:
classical_df = pd.read_csv(r'D:\ProfAjaz\Experiment#1\archived_result\new_result\results_f14_f23\benchmark_summary.csv')

In [14]:
classical_df

,Function,Optimizer,Mean_Fitness,Std_Fitness,Mean_Expl,Mean_Exploit,AUC_Expl,AUC_Exploit,Mean_Expl_Hussain,Mean_Exploit_Hussain,AUC_Expl_Hussain,AUC_Exploit_Hussain,Avg_Conv_Iter,Avg_Xover_Point,Avg_Xover_Hussain
0,F14,GWO,8.578881,5.813891e+00,9.170885,90.829115,9.070823,90.729177,9.170885,90.829115,9.070823,90.729177,159.200000,2.866667,2.866667
1,F14,PSO,9.887800,7.367391e+00,0.829336,99.170664,0.729336,99.070664,0.829336,99.170664,0.729336,99.070664,6.433333,1.233333,1.233333
2,F14,DE,1.771727,3.247686e+00,2.463503,97.536497,2.378990,97.421010,2.915642,97.084358,2.815642,96.984358,28.800000,6.166667,11.033333
3,F14,AGOA,1.588587,1.771586e+00,28.210689,71.789311,28.102969,71.697031,36.136929,63.863071,35.999169,63.800831,201.666667,5.633333,25.100000
4,F14,EES,5.277932,5.624928e+00,4.428106,95.571894,4.360391,95.439208,6.357715,93.642285,6.257250,93.542350,56.100000,3.033333,8.366667
5,F15,GWO,0.003835,7.400646e-03,11.376698,88.623302,11.276663,88.523337,11.376698,88.623302,11.276663,88.523337,197.000000,3.866667,3.866667
6,F15,PSO,0.009973,8.555723e-03,0.755069,99.244931,0.655069,99.144931,0.755069,99.244931,0.655069,99.144931,7.066667,1.300000,1.300000
7,F15,DE,0.002611,5.931680e-03,3.747637,96.252363,3.650983,96.149017,3.823695,96.176305,3.724519,96.075481,34.200000,15.500000,15.800000
8,F15,AGOA,0.000412,7.928260e-05,37.808868,62.191132,37.685649,62.114351,41.451651,58.548349,41.316482,58.483518,499.000000,60.766667,103.466667
9,F15,EES,0.001007,3.598220e-03,10.205267,89.794733,10.110649,89.688950,10.812563,89.187437,10.712290,89.087309,166.866667,17.133333,19.200000
10,F16,GWO,-1.031628,2.515091e-08,3.907858,96.092142,3.807835,95.992165,3.907858,96.092142,3.807835,95.992165,7.866667,2.266667,2.266667
11,F16,PSO,-1.031628,4.385030e-16,0.740939,99.259061,0.640939,99.159061,0.740136,99.259864,0.640244,99.159756,6.366667,1.333333,1.333333
12,F16,DE,-1.031628,4.440892e-16,1.468362,98.531638,1.385474,98.414526,1.773605,98.226395,1.673605,98.126395,24.766667,2.600000,3.200000
13,F16,AGOA,-1.031628,1.816014e-06,21.255284,78.744716,21.160586,78.639414,28.379187,71.620813,28.253052,71.546948,193.966667,1.866667,2.733333
14,F16,EES,-1.031628,4.440892e-16,2.081413,97.918587,2.019634,97.779965,6.662101,93.337899,6.567932,93.231668,4.100000,1.033333,10.666667
15,F17,GWO,0.397889,1.216488e-06,19.793594,80.206406,19.693453,80.106547,19.793594,80.206406,19.693453,80.106547,337.566667,3.166667,3.166667
16,F17,PSO,0.397887,0.000000e+00,0.665851,99.334149,0.565851,99.234149,0.665851,99.334149,0.565851,99.234149,5.300000,1.466667,1.466667
17,F17,DE,0.397887,0.000000e+00,0.731693,99.268307,0.641992,99.158008,0.815736,99.184264,0.715736,99.084264,8.100000,2.566667,2.966667
18,F17,AGOA,0.399077,6.408640e-03,23.473851,76.526149,23.368340,76.431660,27.516242,72.483758,27.393017,72.406983,62.433333,4.700000,7.000000
19,F17,EES,0.397887,0.000000e+00,1.747355,98.252645,1.655183,98.144417,1.897418,98.102582,1.797217,98.002382,19.266667,6.600000,7.300000
20,F18,GWO,3.000031,3.637914e-05,12.023234,87.976766,11.923151,87.876849,12.023234,87.976766,11.923151,87.876849,201.800000,2.866667,2.866667
21,F18,PSO,3.000000,1.873614e-15,0.742437,99.257563,0.642437,99.157563,0.739742,99.260258,0.639998,99.160002,6.566667,1.333333,1.333333
22,F18,DE,3.000000,1.956010e-15,1.086456,98.913544,1.000492,98.799508,1.258779,98.741221,1.158779,98.641221,11.000000,5.333333,5.933333
23,F18,AGOA,3.000000,1.281975e-15,24.968150,75.031850,24.860031,74.939969,29.952689,70.047311,29.823078,69.976922,107.066667,8.566667,19.066667
24,F18,EES,3.000000,1.538370e-15,3.652972,96.347028,3.562431,96.237169,4.025321,95.974679,3.925147,95.874452,48.500000,9.166667,10.933333
25,F19,GWO,-0.427897,1.023698e-01,31.146938,68.853062,31.046691,68.753309,29.630333,70.369667,29.534435,70.265565,378.533333,90.666667,79.100000
26,F19,PSO,-0.420933,1.035469e-01,0.739366,99.260634,0.639366,99.160634,0.739366,99.260634,0.639366,99.160634,6.900000,1.366667,1.366667
27,F19,DE,-0.504517,3.750938e-02,2.401346,97.598654,2.308330,97.491670,2.496535,97.503465,2.399479,97.400521,17.400000,12.966667,12.800000
28,F19,AGOA,-0.511483,2.220446e-16,32.483337,67.516663,32.349582,67.450418,31.485495,68.514505,31.355815,68.444185,486.300000,25.933333,25.066667
29,F19,EES,-0.511483,2.220446e-16,7.878922,92.121078,7.793036,92.006563,8.523624,91.476376,8.429066,91.370533,126.933333,14.733333,16.066667
30,F20,GWO,-3.224702,8.122009e-02,31.089404,68.910596,30.989148,68.810852,30.891410,69.108590,30.791777,69.008223,413.600000,46.433333,43.300000
31,F20,PSO,-3.182424,1.547881e-01,0.794228,99.205772,0.694228,99.105772,0.794228,99.205772,0.694228,99.105772,7.233333,1.500000,1.500000
32,F20,DE,-3.254622,5.891578e-02,3.261143,96.738857,3.164572,96.635428,3.325360,96.674640,3.226228,96.573772,30.433333,14.933333,15.500000
33,F20,AGOA,-3.302180,4.430885e-02,32.389782,67.610218,32.258988,67.541012,31.284416,68.715584,31.158041,68.641959,499.000000,39.500000,38.000000
34,F20,EES,-3.282350,5.603709e-02,5.428333,94.571667,5.330165,94.469434,5.493589,94.506411,5.392867,94.406732,62.766667,11.300000,12.433333
35,F21,GWO,-9.476479,1.721252e+00,32.860618,67.139382,32.760387,67.039613,32.330785,67.669215,32.231908,67.568092,396.866667,88.066667,84.700000
36,F21,PSO,-5.171897,3.161704e+00,0.795077,99.204923,0.695077,99.104923,0.795077,99.204923,0.695077,99.104923,7.266667,1.366667,1.366667
37,F21,DE,-9.069337,2.471364e+00,3.808385,96.191615,3.717904,96.082096,4.189874,95.810126,4.090127,95.709873,35.800000,15.133333,20.066667
38,F21,AGOA,-6.414665,2.254421e+00,38.318148,61.681852,38.183824,61.616176,37.137077,62.862923,37.006891,62.793109,499.000000,79.033333,76.833333
39,F21,EES,-6.924465,2.456699e+00,7.074630,92.925370,7.022671,92.776929,11.612727,88.387273,11.518834,88.280766,106.433333,6.400000,21.633333
40,F22,GWO,-10.224028,9.538018e-01,29.723487,70.276513,29.623277,70.176723,29.662402,70.337598,29.562720,70.237280,390.766667,60.133333,60.133333
41,F22,PSO,-5.643189,3.662518e+00,0.751183,99.248817,0.651183,99.148817,0.751183,99.248817,0.651183,99.148817,5.966667,1.200000,1.200000
42,F22,DE,-9.925751,1.789761e+00,2.643325,97.356675,2.553467,97.246533,2.928983,97.071017,2.829136,96.970864,28.766667,9.700000,12.533333
43,F22,AGOA,-6.327901,2.248107e+00,37.653051,62.346949,37.519571,62.280429,36.645540,63.354460,36.515654,63.284346,499.000000,77.133333,72.333333
44,F22,EES,-7.390955,2.633905e+00,9.543025,90.456975,9.489184,90.310416,15.485834,84.514166,15.394807,84.404793,160.700000,15.500000,33.533333
45,F23,GWO,-10.278637,1.375584e+00,30.868292,69.131708,30.768083,69.031917,30.663115,69.336885,30.563542,69.236458,400.733333,67.966667,65.900000
46,F23,PSO,-5.558176,3.206552e+00,0.835368,99.164632,0.735368,99.064632,0.823736,99.176264,0.724408,99.075592,8.233333,1.633333,1.633333
47,F23,DE,-9.787232,2.255206e+00,2.726141,97.273859,2.634497,97.165503,2.952040,97.047960,2.852071,96.947929,29.033333,9.600000,11.766667
48,F23,AGOA,-7.111388,2.606051e+00,40.652814,59.347186,40.521118,59.278882,40.217011,59.782989,40.086720,59.713280,499.000000,119.133333,118.366667
49,F23,EES,-7.291652,2.649333e+00,12.418801,87.581199,12.352343,87.447256,18.013747,81.986253,17.914456,81.885143,182.300000,19.733333,47.666667

In [15]:
fitness_cols = ['Mean_Fitness', 'Std_Fitness']
percent_cols = ['Mean_Expl', 'Mean_Exploit', 'AUC_Expl', 'AUC_Exploit', 
                'Mean_Expl_Hussain', 'Mean_Exploit_Hussain', 'AUC_Expl_Hussain', 'AUC_Exploit_Hussain']
iter_cols = ['Avg_Conv_Iter', 'Avg_Xover_Point', 'Avg_Xover_Hussain']


for col in fitness_cols + percent_cols + iter_cols:
    classical_df[col] = pd.to_numeric(classical_df[col], errors='coerce')


summary_df = classical_df.groupby('Optimizer').agg({
    'Mean_Fitness': 'mean',
    'Std_Fitness': 'mean',
    'Mean_Expl': 'mean',
    'Mean_Exploit': 'mean',
    'AUC_Expl': 'mean',
    'AUC_Exploit': 'mean',
    'Mean_Expl_Hussain': 'mean',
    'Mean_Exploit_Hussain': 'mean',
    'Avg_Conv_Iter': 'mean',
    'Avg_Xover_Point': 'mean',
    'Avg_Xover_Hussain': 'mean'
}).reset_index()


display_df = summary_df.copy()


for col in fitness_cols:
    display_df[col] = display_df[col].apply(lambda x: f"{x:.2e}")


for col in percent_cols:
    if col in display_df.columns:
        display_df[col] = display_df[col].apply(lambda x: f"{x:.2f}")


for col in iter_cols:
    display_df[col] = display_df[col].round(0).astype(int)

print("--- SUMMARY AVERAGED (F14-F23 Fix Dimension) ---")
print(display_df.to_string(index=False))

--- SUMMARY AVERAGED (F14-F23 Fix Dimension) ---
Optimizer Mean_Fitness Std_Fitness Mean_Expl Mean_Exploit AUC_Expl AUC_Exploit Mean_Expl_Hussain Mean_Exploit_Hussain  Avg_Conv_Iter  Avg_Xover_Point  Avg_Xover_Hussain
     AGOA    -1.97e+00    8.93e-01     31.72        68.28    31.60       68.20             34.02                65.98            355               42                 49
       DE    -2.84e+00    9.87e-01      2.43        97.57     2.34       97.46              2.65                97.35             25                9                 11
      EES    -1.78e+00    1.34e+00      6.45        93.55     6.37       93.43              8.89                91.11             93               10                 19
      GWO    -2.27e+00    1.01e+00     21.20        78.80    21.10       78.70             20.95                79.05            288               37                 35
      PSO    -7.71e-01    1.77e+00      0.76        99.24     0.66       99.14              0.76                99.24              7                1                  1

In [16]:
pd.read_csv(r'D:\ProfAjaz\Experiment#1\archived_result\new_result\results_f14_f23\friedman_ranks.csv')

   Function Optimizer  Rank
0       F14       PSO     1
1       F14        DE     2
2       F14      AGOA     3
3       F14       GWO     4
4       F14       EES     5
5       F15       EES     1
6       F15      AGOA     2
7       F15        DE     3
8       F15       GWO     4
9       F15       PSO     5
10      F16       PSO     1
11      F16        DE     2
12      F16      AGOA     3
13      F16       EES     4
14      F16       GWO     5
15      F17       PSO     1
16      F17        DE     2
17      F17      AGOA     3
18      F17       EES     4
19      F17       GWO     5
20      F18       PSO     1
21      F18        DE     2
22      F18      AGOA     3
23      F18       EES     4
24      F18       GWO     5
25      F19       PSO     1
26      F19        DE     2
27      F19      AGOA     3
28      F19       EES     4
29      F19       GWO     5
30      F20      AGOA     1
31      F20       PSO     2
32      F20        DE     3
33      F20       EES     4
34      F20       GWO     5
35      F21        DE     1
36      F21      AGOA     2
37      F21       GWO     3
38      F21       EES     4
39      F21       PSO     5
40      F22        DE     1
41      F22      AGOA     2
42      F22       EES     3
43      F22       GWO     4
44      F22       PSO     5
45      F23        DE     1
46      F23      AGOA     2
47      F23       PSO     3
48      F23       EES     4
49      F23       GWO     5

In [17]:
df_total = classical_df 


corr_val, p_val = stats.spearmanr(df_total['Mean_Expl'], df_total['Mean_Expl_Hussain'])

print(f"--- Spearman Correlation Results F14 - F23 (Fix Dimension) ---")
print(f"Correlation Coefficient: {corr_val:.4f}")
print(f"P-value: {p_val:.4e}")

--- Spearman Correlation Results F14 - F23 (Fix Dimension) ---
Correlation Coefficient: 0.9842
P-value: 1.0135e-37

# CEC 2020

In [18]:
cec_df = pd.read_csv(r'D:\ProfAjaz\Experiment#1\archived_result\new_result\results_cec2020\cec2020_summary.csv')

In [19]:
cec_df

,Function,Optimizer,Mean_Fitness,Std_Fitness,Mean_Expl,Mean_Exploit,AUC_Expl,AUC_Exploit,Mean_Expl_Hussain,Mean_Exploit_Hussain,AUC_Expl_Hussain,AUC_Exploit_Hussain,Avg_Conv_Iter,Avg_Xover_Point,Avg_Xover_Hussain
0,F1,GWO,2.061521e+09,1.292122e+09,15.164840,84.835160,15.139834,84.810166,15.164840,84.835160,15.139834,84.810166,1264.866667,5.433333,5.433333
1,F1,PSO,3.826632e+10,1.172263e+10,0.184622,99.815378,0.159622,99.790378,0.184622,99.815378,0.159622,99.790378,6.100000,1.366667,1.366667
2,F1,DE,3.392554e+03,3.408294e+03,2.199806,97.800194,2.174695,97.775305,2.188418,97.811582,2.163435,97.786565,103.466667,26.766667,26.600000
3,F1,AGOA,1.000000e+02,1.850610e-05,29.058364,70.941636,29.027636,70.922364,30.813982,69.186018,30.781411,69.168589,1999.000000,37.666667,40.600000
4,F1,EES,2.882639e+03,3.200353e+03,0.796264,99.203736,0.776701,99.173274,1.036381,98.963619,1.011359,98.938616,44.166667,2.733333,4.333333
5,F2,GWO,4.068044e+03,8.994601e+02,14.653848,85.346152,14.628842,85.321158,14.653848,85.346152,14.628842,85.321158,1145.533333,10.966667,10.966667
6,F2,PSO,7.039004e+03,6.292855e+02,0.421718,99.578282,0.396718,99.553282,0.421718,99.578282,0.396718,99.553282,10.866667,1.333333,1.333333
7,F2,DE,8.073666e+03,3.760436e+02,100.135489,-0.135489,100.085496,-0.135496,90.965034,9.034966,90.919620,9.030380,1999.000000,2000.000000,2000.000000
8,F2,AGOA,3.754035e+03,4.399668e+02,95.487300,4.512700,95.439063,4.510937,95.968013,4.031987,95.919528,4.030472,1999.000000,2000.000000,2000.000000
9,F2,EES,4.953371e+03,6.030678e+02,12.920964,87.079036,12.900577,87.049398,15.493539,84.506461,15.468919,84.481056,679.633333,144.700000,234.033333
10,F3,GWO,5.829412e+04,4.209764e+04,15.299972,84.700028,15.274965,84.675035,15.299972,84.700028,15.274965,84.675035,1270.200000,5.666667,5.666667
11,F3,PSO,1.071327e+06,3.475964e+05,0.195672,99.804328,0.170672,99.779328,0.195672,99.804328,0.170672,99.779328,6.300000,1.466667,1.466667
12,F3,DE,9.082740e+02,3.178743e+01,2.328140,97.671860,2.302953,97.647047,2.313580,97.686420,2.288547,97.661453,98.766667,25.800000,25.700000
13,F3,AGOA,7.897794e+02,1.113373e+01,29.029963,70.970037,28.999197,70.950803,30.481898,69.518102,30.449608,69.500392,1999.000000,38.900000,41.266667
14,F3,EES,1.198721e+03,2.995558e+02,0.857243,99.142757,0.837877,99.112098,1.114523,98.885477,1.089510,98.860465,50.066667,2.600000,4.300000
15,F4,GWO,1.971096e+03,1.364763e+02,16.506028,83.493972,16.481020,83.468980,16.506028,83.493972,16.481020,83.468980,1335.400000,5.966667,5.966667
16,F4,PSO,3.512444e+05,5.991562e+05,0.184751,99.815249,0.159751,99.790249,0.184751,99.815249,0.159751,99.790249,6.833333,1.400000,1.400000
17,F4,DE,1.915705e+03,9.417766e-01,10.525940,89.474060,10.498593,89.451407,10.353207,89.646793,10.326309,89.623691,182.166667,32.433333,31.533333
18,F4,AGOA,1.909663e+03,1.509828e+00,33.350811,66.649189,33.318575,66.631425,34.837213,65.162787,34.803544,65.146456,1999.000000,57.900000,60.933333
19,F4,EES,1.919391e+03,7.380282e+00,1.651814,98.348186,1.628965,98.321010,1.811909,98.188091,1.786895,98.163080,50.600000,9.433333,11.266667
20,F5,GWO,5.090051e+05,4.420066e+05,14.941787,85.058213,14.916779,85.033221,14.941787,85.058213,14.916779,85.033221,1187.900000,7.533333,7.533333
21,F5,PSO,3.948091e+07,5.418823e+07,0.181752,99.818248,0.156752,99.793248,0.181752,99.818248,0.156752,99.793248,5.766667,1.266667,1.266667
22,F5,DE,3.588448e+04,1.767242e+04,21.259212,78.740788,21.232603,78.717397,20.252527,79.747473,20.227188,79.722812,1092.866667,233.833333,213.333333
23,F5,AGOA,1.665627e+04,7.465595e+03,37.002212,62.997788,36.970256,62.979744,37.442567,62.557433,37.410235,62.539765,1999.000000,308.433333,316.633333
24,F5,EES,1.994476e+04,1.241281e+04,5.610890,94.389110,5.586911,94.363064,5.872013,94.127987,5.846959,94.103016,249.033333,22.833333,25.533333
25,F6,GWO,3.195210e+04,1.601216e+04,14.514829,85.485171,14.489823,85.460177,14.514829,85.485171,14.489823,85.460177,1161.066667,7.233333,7.233333
26,F6,PSO,6.579812e+07,3.279799e+08,0.170967,99.829033,0.145967,99.804033,0.170967,99.829033,0.145967,99.804033,4.733333,1.333333,1.333333
27,F6,DE,2.284244e+03,1.885448e+03,20.953185,79.046815,20.925835,79.024165,20.389091,79.610909,20.362491,79.587509,1216.366667,159.400000,149.100000
28,F6,AGOA,1.981723e+03,3.281355e+02,36.177744,63.822256,36.145338,63.804662,37.057521,62.942479,37.024326,62.925674,1999.000000,211.966667,222.966667
29,F6,EES,2.034119e+03,2.704891e+02,3.621633,96.378367,3.598055,96.351920,3.848117,96.151883,3.823091,96.126884,168.500000,11.000000,12.266667
30,F7,GWO,1.075031e+06,5.422242e+05,14.098929,85.901071,14.073923,85.876077,14.098929,85.901071,14.073923,85.876077,1144.700000,7.166667,7.166667
31,F7,PSO,3.032535e+08,7.860431e+08,0.171559,99.828441,0.146559,99.803441,0.171559,99.828441,0.146559,99.803441,5.366667,1.300000,1.300000
32,F7,DE,2.178843e+04,1.732566e+04,17.287504,82.712496,17.261263,82.688737,16.757906,83.242094,16.732460,83.217540,888.966667,161.733333,147.066667
33,F7,AGOA,8.087846e+03,4.349021e+03,37.068043,62.931957,37.036034,62.913966,37.549309,62.450691,37.516882,62.433118,1999.000000,333.766667,337.600000
34,F7,EES,1.276885e+04,8.509062e+03,5.000324,94.999676,4.976342,94.973633,5.242267,94.757733,5.217196,94.732779,205.833333,13.600000,14.733333
35,F8,GWO,2.397129e+03,1.367306e+01,16.343595,83.656405,16.318587,83.631413,16.343595,83.656405,16.318587,83.631413,1313.866667,6.566667,6.566667
36,F8,PSO,3.856189e+03,8.552513e+02,0.187054,99.812946,0.162054,99.787946,0.187054,99.812946,0.162054,99.787946,6.000000,1.333333,1.333333
37,F8,DE,2.370846e+03,5.925211e+00,2.797882,97.202118,2.772395,97.177605,2.724018,97.275982,2.699206,97.250794,147.000000,26.400000,25.366667
38,F8,AGOA,2.366671e+03,3.263010e+00,30.356472,69.643528,30.324868,69.625132,31.047619,68.952381,31.015301,68.934699,1999.000000,48.000000,49.300000
39,F8,EES,2.511323e+03,1.498402e+02,0.980171,99.019829,0.960795,98.989180,1.272624,98.727376,1.247790,98.702185,53.766667,5.666667,11.466667
40,F9,GWO,4.804505e+03,1.122129e+03,17.074997,82.925003,17.049989,82.900011,17.074997,82.925003,17.049989,82.900011,1332.933333,6.100000,6.100000
41,F9,PSO,2.720426e+04,5.352784e+03,0.195818,99.804182,0.170818,99.779182,0.195818,99.804182,0.170818,99.779182,5.433333,1.433333,1.433333
42,F9,DE,2.600000e+03,5.444322e-13,2.018128,97.981872,1.993324,97.956676,2.032070,97.967930,2.007098,97.942902,98.833333,23.066667,23.333333
43,F9,AGOA,2.623021e+03,6.964970e+01,29.359863,70.640137,29.329548,70.620452,31.332872,68.667128,31.300525,68.649475,1999.000000,45.533333,49.866667
44,F9,EES,2.636866e+03,1.130974e+02,0.856293,99.143707,0.837008,99.112967,1.123913,98.876087,1.098900,98.851075,48.500000,2.633333,4.033333
45,F10,GWO,3.038832e+03,5.545798e+01,14.944504,85.055496,14.919496,85.030504,14.944504,85.055496,14.919496,85.030504,1256.100000,6.066667,6.066667
46,F10,PSO,5.445522e+03,1.441338e+03,0.185692,99.814308,0.160692,99.789308,0.184196,99.815804,0.159280,99.790720,6.600000,1.433333,1.433333
47,F10,DE,2.920939e+03,2.012024e+00,2.914760,97.085240,2.889660,97.060340,2.894793,97.105207,2.869869,97.080131,131.566667,31.800000,31.333333
48,F10,AGOA,2.920921e+03,1.719363e-01,31.258712,68.741288,31.227617,68.722383,32.912391,67.087609,32.879659,67.070341,1999.000000,51.700000,55.500000
49,F10,EES,2.940185e+03,2.153849e+01,1.015999,98.984001,0.994572,98.955403,1.188317,98.811683,1.163304,98.786671,45.833333,4.166667,5.300000

In [20]:
fitness_cols = ['Mean_Fitness', 'Std_Fitness']
percent_cols = ['Mean_Expl', 'Mean_Exploit', 'AUC_Expl', 'AUC_Exploit', 
                'Mean_Expl_Hussain', 'Mean_Exploit_Hussain', 'AUC_Expl_Hussain', 'AUC_Exploit_Hussain']
iter_cols = ['Avg_Conv_Iter', 'Avg_Xover_Point', 'Avg_Xover_Hussain']


for col in fitness_cols + percent_cols + iter_cols:
    cec_df[col] = pd.to_numeric(cec_df[col], errors='coerce')


summary_df = cec_df.groupby('Optimizer').agg({
    'Mean_Fitness': 'mean',
    'Std_Fitness': 'mean',
    'Mean_Expl': 'mean',
    'Mean_Exploit': 'mean',
    'AUC_Expl': 'mean',
    'AUC_Exploit': 'mean',
    'Mean_Expl_Hussain': 'mean',
    'Mean_Exploit_Hussain': 'mean',
    'Avg_Conv_Iter': 'mean',
    'Avg_Xover_Point': 'mean',
    'Avg_Xover_Hussain': 'mean'
}).reset_index()


display_df = summary_df.copy()


for col in fitness_cols:
    display_df[col] = display_df[col].apply(lambda x: f"{x:.2e}")


for col in percent_cols:
    if col in display_df.columns:
        display_df[col] = display_df[col].apply(lambda x: f"{x:.2f}")


for col in iter_cols:
    display_df[col] = display_df[col].round(0).astype(int)

print("--- SUMMARY AVERAGED (CEC 2020) ---")
print(display_df.to_string(index=False))

--- SUMMARY AVERAGED (CEC 2020) ---
Optimizer Mean_Fitness Std_Fitness Mean_Expl Mean_Exploit AUC_Expl AUC_Exploit Mean_Expl_Hussain Mean_Exploit_Hussain  Avg_Conv_Iter  Avg_Xover_Point  Avg_Xover_Hussain
     AGOA     4.12e+03    1.27e+03     38.81        61.19    38.78       61.17             39.94                60.06           1999              313                317
       DE     8.21e+03    4.07e+03     18.24        81.76    18.21       81.74             17.09                82.91            596              272                267
      EES     5.38e+03    2.56e+03      3.33        96.67     3.31       96.64              3.80                96.20            160               22                 33
      GWO     2.06e+08    1.29e+08     15.35        84.65    15.33       84.62             15.35                84.65           1241                7                  7
      PSO     3.87e+09    1.29e+09      0.21        99.79     0.18       99.77              0.21                99.79              6                1                  1

In [25]:
pd.read_csv(r'D:\ProfAjaz\Experiment#1\archived_result\new_result\results_cec2020\cec2020_friedman_ranks.csv')

   Function Optimizer  Rank
0        F1      AGOA     1
1        F1       EES     2
2        F1        DE     3
3        F1       GWO     4
4        F1       PSO     5
5        F2      AGOA     1
6        F2       GWO     2
7        F2       EES     3
8        F2       PSO     4
9        F2        DE     5
10       F3      AGOA     1
11       F3        DE     2
12       F3       EES     3
13       F3       GWO     4
14       F3       PSO     5
15       F4      AGOA     1
16       F4        DE     2
17       F4       EES     3
18       F4       GWO     4
19       F4       PSO     5
20       F5      AGOA     1
21       F5       EES     2
22       F5        DE     3
23       F5       GWO     4
24       F5       PSO     5
25       F6      AGOA     1
26       F6       EES     2
27       F6        DE     3
28       F6       GWO     4
29       F6       PSO     5
30       F7      AGOA     1
31       F7       EES     2
32       F7        DE     3
33       F7       GWO     4
34       F7       PSO     5
35       F8      AGOA     1
36       F8        DE     2
37       F8       GWO     3
38       F8       EES     4
39       F8       PSO     5
40       F9        DE     1
41       F9      AGOA     2
42       F9       EES     3
43       F9       GWO     4
44       F9       PSO     5
45      F10      AGOA     1
46      F10        DE     2
47      F10       EES     3
48      F10       GWO     4
49      F10       PSO     5

In [22]:
df_total = cec_df 


corr_val, p_val = stats.spearmanr(df_total['Mean_Expl'], df_total['Mean_Expl_Hussain'])

print(f"--- Spearman Correlation Results F1 - F10 (100D) ---")
print(f"Correlation Coefficient: {corr_val:.4f}")
print(f"P-value: {p_val:.4e}")

--- Spearman Correlation Results F1 - F10 (100D) ---
Correlation Coefficient: 0.9964
P-value: 3.0356e-53